# Encoding: UTF-8 with BOM.
# 历史报表：把 ai-history.jsonl 的采样点整理成按天汇总与月度报表，并生成
# CSV / Markdown / HTML 三种导出内容。
#
# 全部是纯函数：不读盘、不联网、不写文件。读历史交给 UsageHistory.ps1，
# 落盘交给主程序的导出入口，所以这里可以直接离线测试。

if (-not (Get-Command ConvertTo-UsageHistoryArray -ErrorAction SilentlyContinue)) {
    $historyHelper = Join-Path $PSScriptRoot 'UsageHistory.ps1'
    if (Test-Path -LiteralPath $historyHelper) { . $historyHelper }
}
if (-not (Get-Command Test-FiniteNumber -ErrorAction SilentlyContinue)) {
    $validationHelper = Join-Path $PSScriptRoot 'UsageValidation.ps1'
    if (Test-Path -LiteralPath $validationHelper) { . $validationHelper }
}
if (-not (Get-Command T -ErrorAction SilentlyContinue)) {
    $stringsHelper = Join-Path $PSScriptRoot 'WidgetStrings.ps1'
    if (Test-Path -LiteralPath $stringsHelper) { . $stringsHelper }
}

$script:UsageReportMonthPattern = '^[0-9]{4}-[0-9]{2}$'

# 月份容错：非法输入回落到“当前月”，保证导出永远有确定的行为。
function ConvertTo-UsageReportMonth {
    param([string]$Value, [datetime]$Now = (Get-Date))
    if ($Value -and $Value -match $script:UsageReportMonthPattern) { return $Value }
    return $Now.ToString('yyyy-MM')
}

function Get-UsageReportMonthStart {
    param([string]$Month, [datetime]$Now = (Get-Date))
    $resolved = ConvertTo-UsageReportMonth -Value $Month -Now $Now
    $parts = $resolved.Split('-')
    return (New-Object datetime ([int]$parts[0]), ([int]$parts[1]), 1)
}

function Test-UsageReportInMonth {
    param([datetime]$Day, [string]$Month, [datetime]$Now = (Get-Date))
    $start = Get-UsageReportMonthStart -Month $Month -Now $Now
    return ($Day -ge $start -and $Day -lt $start.AddMonths(1))
}

function Get-UsageReportNumber {
    param($Value)
    if (-not (Test-FiniteNumber $Value)) { return '' }
    return ([double]$Value).ToString('0.##', [Globalization.CultureInfo]::InvariantCulture)
}

# 语言包缺键时 T 会原样返回键名，这时保留内置英文文案，
# 避免报表里出现 report.colSamples 这类键名。
function Use-UsageReportLabel {
    param($Value, [string]$Key, [string]$Fallback)
    $text = [string]$Value
    if (-not $text -or $text -eq $Key) { return $Fallback }
    return $text
}

# 报表文案：语言包缺键时回落到内置英文文案。
function Get-UsageReportLabels {
    $labels = @{
        Title        = 'AI usage report'
        Heading      = 'Monthly report'
        GeneratedAt  = 'Generated at {0}'
        Provider     = 'Provider'
        Samples      = 'Samples'
        Days         = 'Days'
        First        = 'First'
        Last         = 'Last'
        Min          = 'Min'
        Max          = 'Max'
        Delta        = 'Change'
        Slope        = 'Slope'
        DailyHeading = 'Daily totals'
        NoData       = 'No history samples for this month'
        PerDay       = '{0} %/day'
        Footer       = 'Generated by AI Usage Widget'
    }
    if (Get-Command T -ErrorAction SilentlyContinue) {
        $labels.Title = (Use-UsageReportLabel (T 'report.title') 'report.title' $labels.Title)
        $labels.Heading = (Use-UsageReportLabel (T 'report.heading') 'report.heading' $labels.Heading)
        $labels.GeneratedAt = (Use-UsageReportLabel (T 'report.generatedAt') 'report.generatedAt' $labels.GeneratedAt)
        $labels.Provider = (Use-UsageReportLabel (T 'report.colProvider') 'report.colProvider' $labels.Provider)
        $labels.Samples = (Use-UsageReportLabel (T 'report.colSamples') 'report.colSamples' $labels.Samples)
        $labels.Days = (Use-UsageReportLabel (T 'report.colDays') 'report.colDays' $labels.Days)
        $labels.First = (Use-UsageReportLabel (T 'report.colFirst') 'report.colFirst' $labels.First)
        $labels.Last = (Use-UsageReportLabel (T 'report.colLast') 'report.colLast' $labels.Last)
        $labels.Min = (Use-UsageReportLabel (T 'report.colMin') 'report.colMin' $labels.Min)
        $labels.Max = (Use-UsageReportLabel (T 'report.colMax') 'report.colMax' $labels.Max)
        $labels.Delta = (Use-UsageReportLabel (T 'report.colDelta') 'report.colDelta' $labels.Delta)
        $labels.Slope = (Use-UsageReportLabel (T 'report.colSlope') 'report.colSlope' $labels.Slope)
        $labels.DailyHeading = (Use-UsageReportLabel (T 'report.dailyHeading') 'report.dailyHeading' $labels.DailyHeading)
        $labels.NoData = (Use-UsageReportLabel (T 'report.noData') 'report.noData' $labels.NoData)
        $labels.PerDay = (Use-UsageReportLabel (T 'report.perDay') 'report.perDay' $labels.PerDay)
        $labels.Footer = (Use-UsageReportLabel (T 'report.footer') 'report.footer' $labels.Footer)
    }
    return $labels
}

# 按天汇总：同一天同一供应商只留一行，First/Last 取当天首末采样，
# Min/Max 取当天极值，Samples 是当天采样次数。
function Get-UsageHistoryDailyRollup {
    param($Records, [string]$Month, [string]$Id, [datetime]$Now = (Get-Date))
    $resolved = ConvertTo-UsageReportMonth -Value $Month -Now $Now
    $buckets = @{}
    $keys = New-Object System.Collections.Generic.List[string]
    foreach ($record in @(ConvertTo-UsageHistoryArray $Records)) {
        if (-not $record) { continue }
        $ts = $record.Ts
        if (-not ($ts -is [datetime])) { continue }
        if (-not (Test-UsageReportInMonth -Day $ts -Month $resolved -Now $Now)) { continue }
        $recordId = [string]$record.Id
        if (-not $recordId) { continue }
        if ($Id -and $recordId -ne $Id) { continue }
        $key = $recordId + '|' + $ts.ToString('yyyy-MM-dd')
        if (-not $buckets.ContainsKey($key)) {
            $buckets[$key] = @{
                Id = $recordId; Day = $ts.Date; DayKey = $ts.ToString('yyyy-MM-dd')
                Samples = 0; First = $null; Last = $null; Min = $null; Max = $null; Sum = 0.0
            }
            [void]$keys.Add($key)
        }
        $bucket = $buckets[$key]
        $pct = [double]$record.Pct
        $bucket.Samples = [int]$bucket.Samples + 1
        if ($null -eq $bucket.First) { $bucket.First = $pct }
        $bucket.Last = $pct
        if ($null -eq $bucket.Min -or $pct -lt [double]$bucket.Min) { $bucket.Min = $pct }
        if ($null -eq $bucket.Max -or $pct -gt [double]$bucket.Max) { $bucket.Max = $pct }
        $bucket.Sum = [double]$bucket.Sum + $pct
    }

    $rollup = @()
    foreach ($key in @($keys | Sort-Object)) {
        $bucket = $buckets[$key]
        $delta = 0.0
        if ($null -ne $bucket.First -and $null -ne $bucket.Last) { $delta = [double]$bucket.Last - [double]$bucket.First }
        $rollup += @{
            Id      = $bucket.Id
            Day     = $bucket.Day
            DayKey  = $bucket.DayKey
            Samples = [int]$bucket.Samples
            First   = $bucket.First
            Last    = $bucket.Last
            Min     = $bucket.Min
            Max     = $bucket.Max
            Delta   = $delta
            Average = ([double]$bucket.Sum / [double]$bucket.Samples)
        }
    }
    # 显式用表达式排序：Windows PowerShell 5.1 不支持按哈希表键名排序。
    return @($rollup | Sort-Object -Property @{ Expression = { $_.DayKey } }, @{ Expression = { $_.Id } })
}

# 月度汇总：每个供应商一行，斜率复用 UsageHistory.ps1 的最小二乘实现。
function Get-UsageHistoryMonthlySummary {
    param($Records, [string]$Month, [datetime]$Now = (Get-Date))
    $resolved = ConvertTo-UsageReportMonth -Value $Month -Now $Now
    $rollup = @(Get-UsageHistoryDailyRollup -Records $Records -Month $resolved -Now $Now)
    $aggregates = @{}
    $ids = New-Object System.Collections.Generic.List[string]
    foreach ($entry in $rollup) {
        $id = [string]$entry.Id
        if (-not $aggregates.ContainsKey($id)) {
            $aggregates[$id] = @{
                Id = $id; Samples = 0; Days = 0; First = $null; Last = $null
                Min = $null; Max = $null; Sum = 0.0; PeakDay = $null; PeakPct = $null; Series = @()
            }
            [void]$ids.Add($id)
        }
        $agg = $aggregates[$id]
        $agg.Samples = [int]$agg.Samples + [int]$entry.Samples
        $agg.Days = [int]$agg.Days + 1
        if ($null -eq $agg.First) { $agg.First = [double]$entry.First }
        $agg.Last = [double]$entry.Last
        if ($null -eq $agg.Min -or [double]$entry.Min -lt [double]$agg.Min) { $agg.Min = [double]$entry.Min }
        if ($null -eq $agg.Max -or [double]$entry.Max -gt [double]$agg.Max) { $agg.Max = [double]$entry.Max }
        $agg.Sum = [double]$agg.Sum + ([double]$entry.Average * [int]$entry.Samples)
        if ($null -eq $agg.PeakPct -or [double]$entry.Last -gt [double]$agg.PeakPct) {
            $agg.PeakPct = [double]$entry.Last
            $agg.PeakDay = $entry.DayKey
        }
        $agg.Series = @($agg.Series) + @(@{ Day = $entry.Day; Pct = [double]$entry.Last })
    }

    $summary = @()
    foreach ($id in @($ids | Sort-Object)) {
        $agg = $aggregates[$id]
        $delta = 0.0
        if ($null -ne $agg.First -and $null -ne $agg.Last) { $delta = [double]$agg.Last - [double]$agg.First }
        $average = 0.0
        if ([int]$agg.Samples -gt 0) { $average = [double]$agg.Sum / [double]$agg.Samples }
        $slope = $null
        try { $slope = Get-UsageTrendSlope $agg.Series } catch { $slope = $null }
        $summary += @{
            Id = $agg.Id; Samples = [int]$agg.Samples; Days = [int]$agg.Days
            First = $agg.First; Last = $agg.Last; Min = $agg.Min; Max = $agg.Max
            Delta = $delta; Average = $average; SlopePerDay = $slope
            PeakDay = $agg.PeakDay; PeakPct = $agg.PeakPct
        }
    }
    return @($summary)
}

# 历史里出现过的月份，新的在前；用于菜单与“最近 N 个月”导出。
function Get-UsageHistoryMonths {
    param($Records, [int]$Limit = 0)
    $months = New-Object System.Collections.Generic.List[string]
    foreach ($record in @(ConvertTo-UsageHistoryArray $Records)) {
        if (-not $record) { continue }
        $ts = $record.Ts
        if (-not ($ts -is [datetime])) { continue }
        $key = $ts.ToString('yyyy-MM')
        if (-not $months.Contains($key)) { [void]$months.Add($key) }
    }
    $sorted = @($months | Sort-Object -Descending)
    if ($Limit -gt 0 -and $sorted.Count -gt $Limit) { $sorted = @($sorted[0..($Limit - 1)]) }
    return @($sorted)
}

function ConvertTo-UsageReportCsv {
    param($Rollup)
    $builder = New-Object System.Text.StringBuilder
    [void]$builder.Append("day,provider,samples,first,last,min,max,delta`r`n")
    foreach ($entry in @($Rollup)) {
        if (-not $entry) { continue }
        $fields = @(
            (ConvertTo-UsageHistoryField ([string]$entry.DayKey))
            (ConvertTo-UsageHistoryField ([string]$entry.Id))
            ([string][int]$entry.Samples)
            (Get-UsageReportNumber $entry.First)
            (Get-UsageReportNumber $entry.Last)
            (Get-UsageReportNumber $entry.Min)
            (Get-UsageReportNumber $entry.Max)
            (Get-UsageReportNumber $entry.Delta)
        )
        [void]$builder.Append(($fields -join ','))
        [void]$builder.Append("`r`n")
    }
    return $builder.ToString()
}

function ConvertTo-UsageReportMarkdownText {
    param($Value)
    $text = [string]$Value
    return $text.Replace('|', '\|').Replace("`r", ' ').Replace("`n", ' ')
}

function ConvertTo-UsageReportMarkdown {
    param($Summary, $Rollup, [string]$Month, [datetime]$GeneratedAt = (Get-Date))
    $labels = Get-UsageReportLabels
    $resolved = ConvertTo-UsageReportMonth -Value $Month
    $lines = New-Object System.Collections.Generic.List[string]
    [void]$lines.Add(('# ' + $labels.Title + ' · ' + $resolved))
    [void]$lines.Add('')
    [void]$lines.Add(($labels.GeneratedAt -f $GeneratedAt.ToString('yyyy-MM-dd HH:mm:ss')))
    [void]$lines.Add('')
    [void]$lines.Add(('## ' + $labels.Heading))
    [void]$lines.Add('')
    $items = @($Summary)
    if ($items.Count -eq 0) {
        [void]$lines.Add($labels.NoData)
    } else {
        [void]$lines.Add(('| {0} | {1} | {2} | {3} | {4} | {5} | {6} | {7} | {8} |' -f
            $labels.Provider, $labels.Samples, $labels.Days, $labels.First, $labels.Last,
            $labels.Min, $labels.Max, $labels.Delta, $labels.Slope))
        [void]$lines.Add('| --- | --- | --- | --- | --- | --- | --- | --- | --- |')
        foreach ($item in $items) {
            $slope = '-'
            if (Test-FiniteNumber $item.SlopePerDay) { $slope = ($labels.PerDay -f (Get-UsageReportNumber $item.SlopePerDay)) }
            [void]$lines.Add(('| {0} | {1} | {2} | {3} | {4} | {5} | {6} | {7} | {8} |' -f
                (ConvertTo-UsageReportMarkdownText $item.Id), [int]$item.Samples, [int]$item.Days,
                (Get-UsageReportNumber $item.First), (Get-UsageReportNumber $item.Last),
                (Get-UsageReportNumber $item.Min), (Get-UsageReportNumber $item.Max),
                (Get-UsageReportNumber $item.Delta), $slope))
        }
    }
    [void]$lines.Add('')
    [void]$lines.Add(('## ' + $labels.DailyHeading))
    [void]$lines.Add('')
    $days = @($Rollup)
    if ($days.Count -eq 0) {
        [void]$lines.Add($labels.NoData)
    } else {
        [void]$lines.Add(('| {0} | {1} | {2} | {3} | {4} | {5} | {6} |' -f
            'Day', $labels.Provider, $labels.Samples, $labels.First, $labels.Last, $labels.Min, $labels.Max))
        [void]$lines.Add('| --- | --- | --- | --- | --- | --- | --- |')
        foreach ($entry in $days) {
            [void]$lines.Add(('| {0} | {1} | {2} | {3} | {4} | {5} | {6} |' -f
                $entry.DayKey, (ConvertTo-UsageReportMarkdownText $entry.Id), [int]$entry.Samples,
                (Get-UsageReportNumber $entry.First), (Get-UsageReportNumber $entry.Last),
                (Get-UsageReportNumber $entry.Min), (Get-UsageReportNumber $entry.Max)))
        }
    }
    [void]$lines.Add('')
    [void]$lines.Add(('> ' + $labels.Footer))
    return (($lines -join "`n") + "`n")
}

function ConvertTo-UsageReportHtmlText {
    param($Value)
    $text = [string]$Value
    return $text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;').Replace('"', '&quot;')
}

function Get-UsageReportHtmlStyle {
    return (@(
        '<style>'
        '  :root { color-scheme: light dark; }'
        '  body { font-family: "Segoe UI", "Microsoft YaHei", system-ui, sans-serif; margin: 32px; line-height: 1.5; }'
        '  h1 { font-size: 20px; margin: 0 0 4px; }'
        '  h2 { font-size: 15px; margin: 28px 0 8px; }'
        '  .meta { color: #6b7280; font-size: 12px; }'
        '  table { border-collapse: collapse; width: 100%; font-size: 13px; }'
        '  th, td { border: 1px solid #d1d5db; padding: 6px 8px; text-align: right; }'
        '  th:first-child, td:first-child { text-align: left; }'
        '  th { background: #f3f4f6; font-weight: 600; }'
        '  tr:nth-child(even) td { background: rgba(127, 127, 127, 0.06); }'
        '  footer { margin-top: 28px; color: #6b7280; font-size: 12px; }'
        '</style>'
    ) -join "`n")
}

# 自包含 HTML：样式内联，不引用任何外部资源，方便直接双击打开或当作附件发送。
function ConvertTo-UsageReportHtml {
    param($Summary, $Rollup, [string]$Month, [datetime]$GeneratedAt = (Get-Date))
    $labels = Get-UsageReportLabels
    $resolved = ConvertTo-UsageReportMonth -Value $Month
    $stamp = (ConvertTo-UsageReportHtmlText ($labels.GeneratedAt -f $GeneratedAt.ToString('yyyy-MM-dd HH:mm:ss')))
    $builder = New-Object System.Text.StringBuilder
    [void]$builder.Append("<!DOCTYPE html>`n<html lang=""en"">`n<head>`n<meta charset=""utf-8"">`n")
    [void]$builder.Append(('<title>{0} · {1}</title>' -f (ConvertTo-UsageReportHtmlText $labels.Title), $resolved) + "`n")
    [void]$builder.Append((Get-UsageReportHtmlStyle) + "`n")
    [void]$builder.Append("</head>`n<body>`n")
    [void]$builder.Append(('<h1>{0} · {1}</h1>' -f (ConvertTo-UsageReportHtmlText $labels.Title), $resolved) + "`n")
    [void]$builder.Append(('<p class="meta">{0}</p>' -f $stamp) + "`n")
    [void]$builder.Append(('<h2>{0}</h2>' -f (ConvertTo-UsageReportHtmlText $labels.Heading)) + "`n")
    $items = @($Summary)
    if ($items.Count -eq 0) {
        [void]$builder.Append(('<p class="meta">{0}</p>' -f (ConvertTo-UsageReportHtmlText $labels.NoData)) + "`n")
    } else {
        [void]$builder.Append("<table>`n<thead><tr>")
        foreach ($head in @($labels.Provider, $labels.Samples, $labels.Days, $labels.First, $labels.Last, $labels.Min, $labels.Max, $labels.Delta, $labels.Slope)) {
            [void]$builder.Append(('<th>{0}</th>' -f (ConvertTo-UsageReportHtmlText $head)))
        }
        [void]$builder.Append("</tr></thead>`n<tbody>`n")
        foreach ($item in $items) {
            $slope = '-'
            if (Test-FiniteNumber $item.SlopePerDay) { $slope = ($labels.PerDay -f (Get-UsageReportNumber $item.SlopePerDay)) }
            [void]$builder.Append('<tr>')
            foreach ($cell in @(
                    (ConvertTo-UsageReportHtmlText $item.Id), [string][int]$item.Samples, [string][int]$item.Days,
                    (Get-UsageReportNumber $item.First), (Get-UsageReportNumber $item.Last),
                    (Get-UsageReportNumber $item.Min), (Get-UsageReportNumber $item.Max),
                    (Get-UsageReportNumber $item.Delta), (ConvertTo-UsageReportHtmlText $slope))) {
                [void]$builder.Append(('<td>{0}</td>' -f $cell))
            }
            [void]$builder.Append("</tr>`n")
        }
        [void]$builder.Append("</tbody>`n</table>`n")
    }
    [void]$builder.Append(('<h2>{0}</h2>' -f (ConvertTo-UsageReportHtmlText $labels.DailyHeading)) + "`n")
    $days = @($Rollup)
    if ($days.Count -eq 0) {
        [void]$builder.Append(('<p class="meta">{0}</p>' -f (ConvertTo-UsageReportHtmlText $labels.NoData)) + "`n")
    } else {
        [void]$builder.Append("<table>`n<thead><tr>")
        foreach ($head in @('Day', $labels.Provider, $labels.Samples, $labels.First, $labels.Last, $labels.Min, $labels.Max)) {
            [void]$builder.Append(('<th>{0}</th>' -f (ConvertTo-UsageReportHtmlText $head)))
        }
        [void]$builder.Append("</tr></thead>`n<tbody>`n")
        foreach ($entry in $days) {
            [void]$builder.Append('<tr>')
            foreach ($cell in @(
                    (ConvertTo-UsageReportHtmlText $entry.DayKey), (ConvertTo-UsageReportHtmlText $entry.Id), [string][int]$entry.Samples,
                    (Get-UsageReportNumber $entry.First), (Get-UsageReportNumber $entry.Last),
                    (Get-UsageReportNumber $entry.Min), (Get-UsageReportNumber $entry.Max))) {
                [void]$builder.Append(('<td>{0}</td>' -f $cell))
            }
            [void]$builder.Append("</tr>`n")
        }
        [void]$builder.Append("</tbody>`n</table>`n")
    }
    [void]$builder.Append(('<footer>{0}</footer>' -f (ConvertTo-UsageReportHtmlText $labels.Footer)) + "`n")
    [void]$builder.Append("</body>`n</html>`n")
    return $builder.ToString()
}

function Get-UsageReportFileName {
    param([string]$Month, [string]$Extension)
    $resolved = ConvertTo-UsageReportMonth -Value $Month
    $ext = [string]$Extension
    if (-not $ext) { $ext = 'csv' }
    return ('ai-usage-report-{0}.{1}' -f $resolved, $ext.TrimStart('.'))
}
